apiVersion: apps/v1
kind: Deployment
metadata: 
  name: todolist-deployment
spec: 
  replicas: 3
  template:
    metadata:
      name: todolist-pod
      labels:
        app: todolist-pod
    spec:
      containers:
        - name: todolist-container-d
          image: todo-list:3.0
          ports:
            - containerPort: 80
  selector: 
    matchLabels:
      app: todolist-pod